version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: petclinic_db
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  app:
    build:
      context: .
      target: prod
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_PROFILES_ACTIVE=mysql
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: petclinic_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-volume:
