version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres_vol:/var/lib/postgresql/data
  app:
    build:
      context: .
      target: dev
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_URL=jdbc:postgresql://db:5432/petclinic
      - SPRING_PROFILES_ACTIVE=postgres

volumes:
  postgres_vol:


